int myInt = 8675309;
short myShort = 32_767;
long myLong = 100_000_000_000;
byte myByte = 255;
sbyte mySbyte = -128;
uint myUint = 49;
ushort myUshort = 9393;
ulong myUlong = 939_393_393_191;
char myChar = 'a';
string myString = "a cool guy 😎";
float myFloat = 123.348484f;
double myDouble = 1.234;
decimal myDecimal = 3.44444m;
bool myBool = true;

Console.WriteLine(myInt);
Console.WriteLine(myShort);
Console.WriteLine(myLong);
Console.WriteLine(myByte);
Console.WriteLine(mySbyte);
Console.WriteLine(myUint);
Console.WriteLine(myUshort);
Console.WriteLine(myUlong);
Console.WriteLine(myChar);
Console.WriteLine(myString);
Console.WriteLine(myFloat);
Console.WriteLine(myDouble);
Console.WriteLine(myDecimal);
Console.WriteLine(myBool);